import { featuredExams } from "../lib/catalog";

const exams = featuredExams;

const categories = [["Teaching", "BPSC · STET · CTET", "▥", "peach"], ["Civil Services", "UPSC · State PSC", "◈", "lavender"], ["Banking & SSC", "IBPS · SBI · CGL", "▤", "mint"], ["Engineering", "GATE · JE · Technical", "⌘", "sky"]];

export default function Home() {
  return <main>
    <nav className="public-nav"><a className="logo" href="#top"><span className="logo-mark">N</span><span>northstar<span className="logo-dot">.</span></span></a><div className="nav-links"><a href="#exams">Explore exams</a><a href="#practice">Practice tests</a><a href="#how-it-works">How it works</a></div><div className="nav-actions"><button className="nav-search" aria-label="Search exams">⌕ <span>Search exams</span></button><a className="login" href="#login">Log in</a><a className="nav-cta" href="#signup">Start for free <span>→</span></a></div><button className="menu-button" aria-label="Open menu">☰</button></nav>
    <section className="hero" id="top"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line" /> INDIA'S FOCUSED MOCK-TEST PLATFORM</div><h1>Practice with purpose.<br /><i>Perform with confidence.</i></h1><p className="hero-lede">Realistic mock tests, clear analytics, and a smarter path to your next exam. Start with one question today.</p><div className="hero-search"><span>⌕</span><input aria-label="Search exams and tests" placeholder="Search an exam, subject, or test series" /><button>Find my test <span>→</span></button></div><div className="hero-proof"><div className="proof-avatars"><span>AK</span><span>RS</span><span>PM</span><b>+</b></div><p><strong>12,000+ learners</strong><br />practising with clarity</p></div></div><div className="hero-art" aria-label="Illustration of a learner studying"><div className="sun-shape" /><div className="art-card card-score"><small>YOUR ACCURACY</small><strong>82<span>.4%</span></strong><div className="tiny-chart"><i /><i /><i /><i /><i /></div></div><div className="art-card card-check"><span>✓</span><div><strong>Session complete</strong><small>+14 points today</small></div></div><div className="person"><div className="hair" /><div className="head" /><div className="body" /><div className="arm" /></div><div className="desk" /><div className="plant">🌿</div><div className="sparkle sparkle-one">✦</div><div className="sparkle sparkle-two">✧</div></div></section>
    <section className="trust-strip"><span>BUILT FOR THE WAY YOU PREPARE</span><div><b>Focus</b><b>Progress</b><b>Confidence</b><b>Momentum</b></div></section>
    <section className="section" id="exams"><div className="section-intro"><div><span className="kicker">FIND YOUR STARTING POINT</span><h2>Exams that matter<br /><em>to your next chapter.</em></h2></div><a className="text-link" href="#all-exams">Browse all exams <span>↗</span></a></div><div className="exam-grid">{exams.map((exam) => <article className={`exam-card ${exam.tone}`} key={exam.title}><div className="exam-visual"><span className="exam-symbol">{exam.symbol}</span><span className="exam-badge">{exam.badge}</span><div className="ring-shape" /></div><div className="exam-body"><small>{exam.meta}</small><h3>{exam.title}</h3><p>{exam.tests}<span> · </span>Free & premium</p><a href={`/exams/${exam.slug}`}>View test series <span>→</span></a></div></article>)}</div></section>
    <section className="section category-section"><div className="section-intro"><div><span className="kicker">EXPLORE BY CATEGORY</span><h2>A better way to<br /><em>find your focus.</em></h2></div><p className="section-note">Everything you need to practise<br />with intention, in one place.</p></div><div className="category-grid">{categories.map(([title, meta, icon, tone]) => <a href="#category" className={`category-card ${tone}`} key={title}><span className="category-icon">{icon}</span><span><strong>{title}</strong><small>{meta}</small></span><b>↗</b></a>)}</div></section>
    <section className="practice-band" id="practice"><div className="practice-copy"><span className="kicker">START SMALL. GO FAR.</span><h2>Your next best<br /><em>practice session.</em></h2><p>Short on time? Make the next 20 minutes count with focused tests built around the topics you need most.</p><a className="dark-button" href="#free-tests">Explore free tests <span>→</span></a></div><div className="practice-list"><div className="practice-item"><div className="practice-number">01</div><div><small>QUICK PRACTICE · 20 MIN</small><h3>Teaching aptitude essentials</h3><p>20 questions <span>·</span> Beginner-friendly</p></div><span className="practice-arrow">↗</span></div><div className="practice-item"><div className="practice-number">02</div><div><small>PREVIOUS YEAR · 45 MIN</small><h3>BPSC TRE General Studies</h3><p>50 questions <span>·</span> Exam-level</p></div><span className="practice-arrow">↗</span></div><div className="practice-item"><div className="practice-number">03</div><div><small>WEAK TOPIC · 15 MIN</small><h3>Reasoning: series & patterns</h3><p>15 questions <span>·</span> Personalised</p></div><span className="practice-arrow">↗</span></div></div></section>
    <section className="feature-section" id="how-it-works"><div className="feature-image"><div className="feature-window"><div className="window-top"><span>northstar</span><i>•••</i></div><div className="window-content"><small>WEEKLY PROGRESS</small><strong>Keep going, Aditi.</strong><div className="progress-number">78<span>%</span></div><div className="progress-line"><i /></div><div className="progress-days"><span>M</span><span>T</span><span>W</span><span className="current">T</span><span>F</span><span>S</span><span>S</span></div></div></div><div className="feature-sticker">✦ <span>small wins<br />add up.</span></div></div><div className="feature-copy"><span className="kicker">CLARITY AFTER EVERY TEST</span><h2>Know exactly<br /><em>what to do next.</em></h2><p>Not just a score. See your accuracy by subject, understand every mistake, and get a clear recommendation for your next session.</p><div className="feature-points"><div><span>01</span><strong>Simple, honest analytics</strong></div><div><span>02</span><strong>Weak-topic recommendations</strong></div><div><span>03</span><strong>Progress you can feel</strong></div></div><a className="text-link" href="#analytics">See how analytics work <span>↗</span></a></div></section>
    <section className="final-cta"><span className="kicker">YOUR PREPARATION, YOUR PACE</span><h2>Ready to make<br /><em>your attempt count?</em></h2><p>Join thousands of learners building their confidence one test at a time.</p><a className="light-button" href="#signup">Create your free account <span>→</span></a></section>
    <footer className="footer"><a className="logo" href="#top"><span className="logo-mark">N</span><span>northstar<span className="logo-dot">.</span></span></a><p>Find your exam. Find your focus. Find your way forward.</p><div className="footer-links"><a href="#exams">Exams</a><a href="#tests">Test series</a><a href="#notifications">Notifications</a><a href="#about">About</a><a href="#support">Support</a></div><small>© 2026 Northstar Learning Technologies <span>·</span> Privacy <span>·</span> Terms</small></footer>
  </main>;
}